default_hour: 9
default_minute: 0
editor: "vim"
encrypt: true
highlight: true
indent_character: "|"
journals:
  default: PLACEHOLDER
linewrap: 79
tagsymbols: "@"
template: false
timeformat: "%Y-%m-%d %H:%M"
version: v2.2
